services:

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app"
    volumes:
      - ./models:/app/models
    restart: unless-stopped
